In [1]:
import numpy as np


a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])

print(np.intersect1d(a, b)) #Sorted 1D array of common and unique elements

[2 4]


In [2]:

def question2(): 
    array = np.zeros(shape=(5,3))
    key = 0
    for i in range(3):
        for x in range(5):
            key+=1
            array[x][i] = key
    return(array)
print(question2())

[[ 1.  6. 11.]
 [ 2.  7. 12.]
 [ 3.  8. 13.]
 [ 4.  9. 14.]
 [ 5. 10. 15.]]


In [14]:
def question3():
    a = np.array([12, 5, 7, 15, 3, 1, 8])
    b = np.array([14, 6, 3, 11, 19, 12, 5])
    print(a)
    print(b)
    answer = []
    index_list = []
    for i in range(7):
        if a[i] in b:
            index_list.append(i)  
    answer = np.delete(a,index_list)
    return answer
print(question3())

[12  5  7 15  3  1  8]
[14  6  3 11 19 12  5]
[ 7 15  1  8]


***Question #4***

I created a numpy array and filled it randomly using numpy random
function, , given a range of 0-65, spread over 35 days. 
On the basis of this array cumulative miles are calculated.
To know the miles covered per day, each element in cumulative_miles array
is subtracted from the previous one and stored in daily_miles array.

In [15]:
def question4():
    array = np.random.randint(0,65,35)
    count = 0
    for i in range(4):
        count+=5
        array[count]=0
    
    cumulative_results = np.zeros(shape=(35))
    for i in range (35):
        if i == 0:
            cumulative_results[i] = array[i]
        else:
            cumulative_results[i] = cumulative_results[i-1]+array[i] 
                
    print('Cumulative miles ', cumulative_results)
    daily_miles_results = np.zeros(shape=(35))
    
    for y in range(35):
        if y == 0:
            daily_miles_results[y] = cumulative_results[y]
        else:
            daily_miles_results[y] = cumulative_results[y]-cumulative_results[y-1]
    print('Miles covered per day ', daily_miles_results)
    
question4()

Cumulative miles  [ 52.  69. 102. 153. 162. 162. 181. 195. 230. 248. 248. 286. 296. 337.
 391. 391. 410. 426. 478. 527. 527. 534. 561. 624. 643. 662. 713. 738.
 747. 791. 793. 812. 817. 824. 828.]
Miles covered per day  [52. 17. 33. 51.  9.  0. 19. 14. 35. 18.  0. 38. 10. 41. 54.  0. 19. 16.
 52. 49.  0.  7. 27. 63. 19. 19. 51. 25.  9. 44.  2. 19.  5.  7.  4.]


***Question #5***

I used numpy.genfromtxt to read the csv file and loaded it as a numpy array.
I used numpy.genfromtxt to read the csv file and loaded it as a numpy array.
The data type of this array is kept 'unicode' because the table's first row has 
string while rest of it is int and float.
To get the desired values from each column, I treated each column separately.
I had to convert the data type of each column to a float. 


In [16]:
def question5():
    
    d=np.genfromtxt('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv',delimiter=',',dtype=np.unicode)
    print(d)
    x=d[1:,2]
    x=x.astype('float64')
    x=x.max()
    print('\n1: Maximum yearly NYC consumption of water in millions of gallons per day:',int(x))
    
    years = len(d)-1
    print('\n2: Number of years presented in this data is '+str(years)+'.\n')
    
    y=d[1:,3]
    y=y.astype('float64')
    
    mean = np.mean(y)
    std_dev = np.std(y)
    
    print('3: Mean and Standard deviation of per capita is',mean,'and',std_dev,'respectively.\n')
    print('4: Increase and decrease in population is as follows:\n')
    population = d[1:,1]
    population = population.astype('float64')
    pop_diff = np.diff(population)
    for i in pop_diff:
        if i < 0:
            print("Decrease in value",i)
        else:
            print("Increase in value",i)
question5()

[['Year' 'New York City Population'
  'NYC Consumption(Million gallons per day)'
  'Per Capita(Gallons per person per day)']
 ['1979' '7102100' '1512' '213']
 ['1980' '7071639' '1506' '213']
 ['1981' '7089241' '1309' '185']
 ['1982' '7109105' '1382' '194']
 ['1983' '7181224' '1424' '198']
 ['1984' '7234514' '1465' '203']
 ['1985' '7274054' '1326' '182']
 ['1986' '7319246' '1351' '185']
 ['1987' '7342476' '1447' '197']
 ['1988' '7353719' '1484' '202']
 ['1989' '7344175' '1402' '191']
 ['1990' '7335650' '1424' '194']
 ['1991' '7374501' '1469' '199']
 ['1992' '7428944' '1369' '184']
 ['1993' '7506166' '1368.5' '182']
 ['1994' '7570458' '1357.7' '179']
 ['1995' '7633040' '1325.7' '174']
 ['1996' '7697812' '1297.9' '169']
 ['1997' '7773443' '1205.5' '155']
 ['1998' '7858259' '1219.5' '155']
 ['1999' '7947660' '1237.2' '156']
 ['2000' '8008278' '1240.4' '155']
 ['2001' '8024963.5' '1184' '148']
 ['2002' '8041649' '1135.6' '141']
 ['2003' '8058334.5' '1093.7' '136']
 ['2004' '8075020' '1099.5